"""
AI service that uses Groq via langchain_groq for all legal analysis.

This service requires a valid GROQ_API_KEY in environment variables.
All responses are generated by LLM, with no mock data fallback.
Provides concise async wrappers that return JSON or text as required by routes.
"""

import os
import json
import asyncio
import traceback
from typing import Any, Dict, List
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

# Load env files
load_dotenv('.env.local', override=True)
load_dotenv('.env', override=False)

MODEL_PRIMARY = "llama-3.1-8b-instant"
MODEL_SECONDARY = MODEL_PRIMARY
MAX_INPUT_LENGTH = 6000
DEFAULT_MAX_TOKENS = 2048


def sanitize_input(text: str) -> str:
    if not isinstance(text, str):
        return ""
    return text.replace("```", "").strip()


def validate_input(text: str):
    if not text or not isinstance(text, str):
        raise ValueError("Input cannot be empty.")
    if len(text) > MAX_INPUT_LENGTH:
        raise ValueError("Input exceeds allowed length.")


def extract_json(text: str) -> Any:
    """Try to extract JSON object or array from response text.
    Prefer parsing whole text; fall back to finding first { or [ and last } or ].
    """
    if not isinstance(text, str):
        raise ValueError("Invalid response type")
    txt = text.strip()
    # direct parse
    try:
        return json.loads(txt)
    except Exception:
        pass
    # fallback: find first { or [ and locate its matching closing bracket
    start = None
    for i, ch in enumerate(txt):
        if ch == '{' or ch == '[':
            start = i
            open_ch = ch
            break
    if start is None:
        raise ValueError('No JSON found in response')

    # Find matching closing bracket using a simple stack while respecting string literals
    stack = []
    in_string = False
    escape = False
    opening = '{' if open_ch == '{' else '['
    closing = '}' if opening == '{' else ']'
    for j in range(start, len(txt)):
        ch = txt[j]
        if in_string:
            if escape:
                escape = False
            elif ch == '\\':
                escape = True
            elif ch == '"':
                in_string = False
            continue
        else:
            if ch == '"':
                in_string = True
                continue
            if ch == opening:
                stack.append(ch)
            elif ch == closing:
                if not stack:
                    # unmatched closer; keep going
                    continue
                stack.pop()
                if not stack:
                    end = j
                    snippet = txt[start:end+1]
                    try:
                        return json.loads(snippet)
                    except Exception:
                        # continue searching in case of nested issues
                        break

    # As a last resort, try to locate any {...} or [...] block by rfind as before
    if open_ch == '{':
        end = txt.rfind('}')
    else:
        end = txt.rfind(']')
    if end == -1 or end <= start:
        raise ValueError('Incomplete JSON in response')
    snippet = txt[start:end+1]
    return json.loads(snippet)


async def safe_invoke(llm: ChatGroq, messages: List, retries: int = 3):
    last_exc = None
    for attempt in range(retries):
        try:
            return await llm.ainvoke(messages)
        except Exception as e:
            last_exc = e
            txt = str(e).lower()
            if 'decommission' in txt or 'model_decommissioned' in txt:
                raise
            if attempt == retries - 1:
                raise
            await asyncio.sleep(2 ** attempt)
    if last_exc:
        raise last_exc


class LLMManager:
    def __init__(self):
        api_key = os.getenv('GROQ_API_KEY', '').strip()
        if not api_key or api_key.startswith('gsk_your'):
            raise ValueError('GROQ_API_KEY environment variable is required but not set or invalid.')
        try:
            self.primary = ChatGroq(groq_api_key=api_key, model_name=MODEL_PRIMARY, temperature=0.3, max_tokens=DEFAULT_MAX_TOKENS)
            self.secondary = ChatGroq(groq_api_key=api_key, model_name=MODEL_SECONDARY, temperature=0.3, max_tokens=DEFAULT_MAX_TOKENS)
        except Exception as e:
            traceback.print_exc()
            raise ValueError(f'Failed to initialize LLM clients: {e}')


_MANAGER: LLMManager | None = None


def get_llm_manager() -> LLMManager:
    global _MANAGER
    if _MANAGER is None:
        _MANAGER = LLMManager()
    return _MANAGER


async def invoke_json_llm(llm: ChatGroq, system_prompt: str, human_prompt: str) -> Any:
    """Invoke the LLM and parse JSON from its response. Raises on failure."""
    if llm is None:
        raise ValueError('LLM client not initialized')
    messages = [SystemMessage(content=system_prompt), HumanMessage(content=human_prompt)]
    try:
        resp = await safe_invoke(llm, messages)
        # extract content
        if hasattr(resp, 'content'):
            content = resp.content
        elif hasattr(resp, 'text'):
            content = resp.text
        else:
            content = str(resp)
        return extract_json(content)
    except Exception as e:
        msg = str(e).lower()
        # try secondary once for model decommission errors
        try:
            if 'decommission' in msg or 'model_not_found' in msg:
                manager = get_llm_manager()
                if hasattr(manager, 'secondary') and manager.secondary is not None and llm is not manager.secondary:
                    resp = await safe_invoke(manager.secondary, messages)
                    if hasattr(resp, 'content'):
                        content = resp.content
                    elif hasattr(resp, 'text'):
                        content = resp.text
                    else:
                        content = str(resp)
                    return extract_json(content)
        except Exception:
            traceback.print_exc()
        traceback.print_exc()
        raise


# ---------------- Service functions ----------------

async def analyze_dispute(dispute_text: str) -> Dict[str, Any]:
    validate_input(dispute_text)
    dispute_text = sanitize_input(dispute_text)
    manager = get_llm_manager()

    system_prompt = (
        'You are a senior legal analyst specializing in Indian law with 20+ years of experience. '
        'Provide comprehensive, precise legal analysis and return ONLY valid JSON with required fields.'
    )
    human_prompt = (
        'Please conduct a comprehensive legal analysis of the following dispute:\n\n'
        + dispute_text + '\n\n'
        'Return JSON with fields: case_classification, legal_domain, primary_issue, legal_summary, probable_remedy, '
        'suggested_lawyer_type, recommended_lawyers, lawyer_request_summary, urgency, portal_recommendation, '
        'legal_risk_assessment, preliminary_legal_opinion'
    )
    raw = await invoke_json_llm(manager.primary, system_prompt, human_prompt)

    # Normalize response to match Pydantic model expectations
    out: Dict[str, Any] = {}
    if not isinstance(raw, dict):
        raise ValueError("LLM returned non-dict response for dispute analysis")

    # Basic string fields
    for k in [
        'case_classification', 'legal_domain', 'primary_issue', 'legal_summary',
        'suggested_lawyer_type', 'lawyer_request_summary', 'urgency', 'portal_recommendation',
        'legal_risk_assessment', 'preliminary_legal_opinion'
    ]:
        out[k] = raw.get(k, '')

    # probable_remedy should be a list
    pr = raw.get('probable_remedy', [])
    if isinstance(pr, str):
        # split on common separators into short items
        items = [s.strip() for s in pr.replace('\n', '. ').split('.') if s.strip()]
        out['probable_remedy'] = items
    elif isinstance(pr, list):
        out['probable_remedy'] = pr
    else:
        out['probable_remedy'] = [str(pr)]

    # recommended_lawyers: ensure list of objects with required fields
    recs = raw.get('recommended_lawyers', [])
    normalized = []
    if isinstance(recs, list):
        for r in recs:
            if isinstance(r, dict):
                name = r.get('name') or r.get('full_name') or r.get('lawyer_name') or ''
                specialization = r.get('specialization') or r.get('area') or ''
                exp = r.get('experience_years') or r.get('experience') or r.get('years') or ''
                # Try to extract numeric years if possible
                try:
                    if isinstance(exp, str) and '+' in exp:
                        exp_num = int(''.join(ch for ch in exp if ch.isdigit()))
                    else:
                        exp_num = int(exp)
                except Exception:
                    exp_num = 0
                success_rate = r.get('success_rate', r.get('win_rate', 'N/A'))
                location = r.get('location', '')
                profile_id = r.get('profile_id', r.get('id', ''))
                contact_option = r.get('contact_option', r.get('contact', ''))
                normalized.append({
                    'name': name,
                    'specialization': specialization,
                    'experience_years': exp_num,
                    'success_rate': success_rate,
                    'location': location,
                    'profile_id': profile_id,
                    'contact_option': contact_option,
                })
            else:
                # if it's a string, place it into a minimal object
                normalized.append({
                    'name': str(r), 'specialization': '', 'experience_years': 0,
                    'success_rate': 'N/A', 'location': '', 'profile_id': '', 'contact_option': ''
                })
    else:
        # not a list
        normalized.append({
            'name': str(recs), 'specialization': '', 'experience_years': 0,
            'success_rate': 'N/A', 'location': '', 'profile_id': '', 'contact_option': ''
        })

    out['recommended_lawyers'] = normalized

    return out


async def perform_rag_search(query: str, document_text: str) -> Dict[str, Any]:
    validate_input(query)
    validate_input(document_text)
    manager = get_llm_manager()

    system_prompt = (
        'You are an advanced legal research specialist. Provide well-researched answers supported by citations.'
    )
    human_prompt = (
        'Context Document:\n' + document_text + '\n\n'
        'Research Query: ' + query + '\n\n'
        'Return JSON with fields: answer, supporting_analysis, applicable_statutes, case_citations, citations, limitations_and_exceptions, practical_implications'
    )
    return await invoke_json_llm(manager.secondary, system_prompt, human_prompt)


async def get_precedent_analysis(document_text: str) -> Dict[str, Any]:
    validate_input(document_text)
    manager = get_llm_manager()

    system_prompt = (
        'You are an expert judicial analyst and senior advocate. Provide detailed analysis of legal documents focusing on precedents and consistency.'
    )
    human_prompt = (
        document_text + '\n\n'
        'Return JSON with fields: caseTitle, keyArguments, influencingStatutes, consistencyCheck, judicialInterpretation, strengths, weaknesses, precedentialValue, recommendations'
    )
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)


async def get_similar_cases(case_facts: str) -> Dict[str, Any]:
    validate_input(case_facts)
    manager = get_llm_manager()

    system_prompt = (
        'You are a leading legal researcher and case law expert. Identify highly relevant similar cases and analyze applicability.'
    )
    human_prompt = (
        case_facts + '\n\n'
        'Identify 5-7 similar cases. Return JSON with: case_context_summary, similar_cases_found (array of case_title, citation_or_year, court_name, summary_of_decision, relevance_score, key_sections_cited, legal_takeaway), comparative_analysis, overall_summary, strength_of_precedents, suggested_action'
    )
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)


async def generate_arguments(case_facts: str, desired_outcome: str, legal_stance: str) -> Dict[str, Any]:
    validate_input(case_facts)
    manager = get_llm_manager()

    system_prompt = (
        'You are a senior advocate skilled in courtroom argumentation. Provide persuasive, well-reasoned arguments.'
    )
    human_prompt = (
        'Case Facts: ' + case_facts + '\n\n'
        'Legal Stance: ' + legal_stance + '\n\n'
        'Desired Outcome: ' + desired_outcome + '\n\n'
        'Return JSON with: core_argument, argument_structure, supporting_points, statutory_authority, case_law_support, counterarguments, evidence_needed, persuasive_elements, weaknesses_to_address, recommended_court_arguments'
    )
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)


async def get_ai_research_summary(case_context: str, similar_cases: dict, rag_result: dict) -> Dict[str, Any]:
    validate_input(case_context)
    manager = get_llm_manager()

    system_prompt = (
        'You are a senior legal strategist and research synthesizer. Connect research into a cohesive legal strategy.'
    )
    human_prompt = (
        'Case Context: ' + case_context + '\n\n'
        'Similar Cases: ' + json.dumps(similar_cases) + '\n\n'
        'RAG Results: ' + json.dumps(rag_result) + '\n\n'
        'Return JSON with: case_summary, final_summary, strategic_insights, strongest_arguments, precedent_application, argument_suggestion, legal_theory_basis, evidence_strategy, procedural_recommendations, risk_factors, likely_judicial_response, alternative_strategies'
    )
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)


async def get_chat_summary(history: List[Dict[str, str]]) -> str:
    manager = get_llm_manager()
    chat_text = '\n'.join(f"{m.get('role','')}: {m.get('text','')}" for m in history)
    system_prompt = 'You are an expert legal analyst skilled at summarizing complex legal discussions.'
    human_prompt = 'Please summarize the following discussion:\n\n' + chat_text + '\n\nReturn a concise professional summary.'
    resp = await safe_invoke(manager.secondary, [SystemMessage(content=system_prompt), HumanMessage(content=human_prompt)])
    if hasattr(resp, 'content'):
        return resp.content
    if hasattr(resp, 'text'):
        return resp.text
    return str(resp)


async def get_suggested_next_steps(history: List[Dict[str, str]]) -> Dict[str, Any]:
    manager = get_llm_manager()
    chat_text = '\n'.join(f"{m.get('role','')}: {m.get('text','')}" for m in history)
    system_prompt = 'You are an experienced legal advisor. Identify recommended next steps.'
    human_prompt = 'Discussion History:\n' + chat_text + '\n\nReturn JSON with immediate_actions, short_term_suggestions, medium_term_suggestions, clarification_needed, documentation_required, deadlines_to_meet, stakeholder_communications, budget_considerations, risk_mitigation, success_metrics'
    return await invoke_json_llm(manager.secondary, system_prompt, human_prompt)


async def generate_legal_draft(draft_type: str, case_context: str, key_points: str) -> str:
    validate_input(case_context)
    validate_input(key_points)
    manager = get_llm_manager()
    system_prompt = 'You are a senior legal drafter producing professional, court-ready documents.'
    human_prompt = 'Document Type: ' + draft_type + '\n\nCase Context: ' + case_context + '\n\nKey Points:\n' + key_points + '\n\nProduce a professional legal draft.'
    resp = await safe_invoke(manager.primary, [SystemMessage(content=system_prompt), HumanMessage(content=human_prompt)])
    if hasattr(resp, 'content'):
        return resp.content
    if hasattr(resp, 'text'):
        return resp.text
    return str(resp)


async def monitor_for_bias(document_text: str) -> Dict[str, Any]:
    validate_input(document_text)
    manager = get_llm_manager()
    system_prompt = 'You are an expert in legal ethics and bias detection. Identify potential bias and unfair language.'
    human_prompt = 'Analyze this document for bias:\n\n' + document_text + '\n\nReturn JSON with has_bias, findings, language_analysis, logical_fallacies, evidentiary_concerns, fairness_score, recommendations'
    return await invoke_json_llm(manager.secondary, system_prompt, human_prompt)


async def generate_case_requests(count: int = 3) -> Any:
    manager = get_llm_manager()
    system_prompt = 'You are an expert legal case coordinator who creates diverse, realistic dispute scenarios.'
    template = (
        'Generate exactly {COUNT} diverse legal dispute case requests for Indian advocates to review.\n\n'
        'For each case request, include these exact fields in a JSON array:\n'
        '- id, userName, caseSummary, legalDomain, urgency, status, timestamp\n\n'
        'Create cases covering: 1) commercial/contract law 2) property/tenancy 3) consumer or employment dispute.\n\n'
        'Return a valid JSON array of objects.'
    )
    human_prompt = template.replace('{COUNT}', str(count))
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)


async def get_judicial_analytics(case_context: str, timeframe: str = 'last_5_years') -> Dict[str, Any]:
    """Request a structured judicial analytics report from the LLM."""
    validate_input(case_context)
    manager = get_llm_manager()

    system_prompt = (
        'You are an expert judicial analyst and data-driven legal strategist. Produce a structured JSON analytics report for judges.'
    )
    human_prompt = (
        'Case Context: ' + case_context + '\n\n'
        f'Timeframe: {timeframe}\n\n'
        'Return a single valid JSON object with the following fields:\n'
        '- cases_per_year: array of {name, value, description}\n'
        '- avg_time_to_disposition_days: number\n'
        '- backlog_size: integer\n'
        '- win_rates_by_case_type: array of {name, value, description}\n'
        '- caseload_distribution: array of {name, value}\n'
        '- time_to_resolution_series: array of {period, value}\n'
        '- precedent_heatmap_summary: array of {name, value}\n'
        '- judge_trend_insights: array of short insight strings\n'
        '- diversity_metrics: array of {name, value, description}\n'
        '- predicted_backlog_trend: array of {period, value}\n'
        '- recommended_resource_actions: array of short action strings\n'
        '\nReturn only valid JSON. Do not include prose outside the JSON.'
    )
    return await invoke_json_llm(manager.primary, system_prompt, human_prompt)
