"""
Judge API Routes
"""
from fastapi import APIRouter, HTTPException, Body
from app.services import ai_service
from app.models import PrecedentAnalysisResult
from app.models import JudicialAnalyticsResult

router = APIRouter()

@router.post("/precedent-analysis")
async def get_precedent_analysis(data: dict = Body(...)) -> PrecedentAnalysisResult:
    """Analyze a judgment for key arguments, influencing statutes, and logical consistency."""
    try:
        document_text = data.get('document_text', '')
        result = await ai_service.get_precedent_analysis(document_text)
        return result
    except Exception as e:
        import traceback
        print(f"Error in get_precedent_analysis: {traceback.format_exc()}")
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/analytics")
async def get_judicial_analytics(data: dict = Body(...)) -> JudicialAnalyticsResult:
    """Return a comprehensive judicial analytics report generated by the LLM."""
    try:
        case_context = data.get('case_context', '')
        timeframe = data.get('timeframe', 'last_5_years')
        result = await ai_service.get_judicial_analytics(case_context, timeframe)
        # Basic type-safety: expect a dict with required keys; Pydantic will validate
        return JudicialAnalyticsResult(**result)
    except Exception as e:
        import traceback
        print(f"Error in get_judicial_analytics: {traceback.format_exc()}")
        raise HTTPException(status_code=500, detail=str(e))
