/**
 * DEPRECATED - This file is no longer used
 *
 * All mock data has been removed from the application.
 * All responses are now generated by LLM through API endpoints.
 *
 * See all data is now generated through:
 * - GET /api/citizen/case-requests - for case requests
 * - POST /api/citizen/analyze-dispute - for dispute analysis
 * - POST /api/advocate/similar-cases - for similar cases
 * - And other endpoints in app/routes/
 *
 * If you see import errors, remove imports from this file and use
 * the actual API endpoints instead.
 */

import type { CaseRequest, CaseChatMessage } from '../types';

export const initialCaseRequests: CaseRequest[] = [];
export const initialChatHistories: Record<string, CaseChatMessage[]> = {};

